### ISSUE TITLE
Validation Scores on nuScenes

### ISSUE THREAD

**Issue by ldkong1205** [haibo-qiu/GFNet#7]
Hi @haibo-qiu, thank you for open-sourcing your work!

Regarding the experimental results of GFNet, could you share with me what score you got on the val set of nuScenes? Thanks!

**Comment by haibo-qiu** [comment]
Hi @ldkong1205,

Here are the results on the val set of nuScenes:

| barrier |  bicycle | bus | car | const-vehicle | motorcycle | pedestrian | traffic-cone | trailer | truck | dri-surface | other-flat | sidewalk |  terrain | manmade | vegetation | mIoU |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | 
| 77.9 | 37.8 | 93.0 | 89.2 | 49.0 | 82.8 | 78.6 | 65.9 | 68.8 | 81.8 | 97.1 | 74.7 | 76.8 | 76.1 | 90.4 | 89.0 | 76.8 |

**Comment by ldkong1205** [comment]
Thank you for your information!
