### ISSUE TITLE
about RV score

### ISSUE THREAD

**Issue by langdaoliu** [haibo-qiu/GFNet#8]
I use GFnet to train my own dataset, and the performance of the RV branch is very low. I canceled all data augmentation operations. The miou of RV is only about 10, have you ever encountered this problem?

**Comment by haibo-qiu** [comment]
Hi @langdaoliu,

I have never got the 10 miou result for the RV branch, which is very strange even though you did not use any data augmentation. I think the potential reasons might come from two aspects.
1. Improper configs. If you only want to use the RV branch, you need to change the following loss settings
https://github.com/haibo-qiu/GFNet/blob/2f28cb4003480eaf7be024cca206cd1d7068a671/configs/resnet_semantickitti.yaml#L27-L32
to
    ```yaml
    loss:
      range_proj: 1.0
      polar_proj: 0.0
      range: 2.0
      polar: 0.0
      fusion: 0.0
    ```
    It's also worth noting that if you only set `range` to 2.0 but `range_proj` to 0.0, then the results from 2D projects will be in a mess as no supervision.

2. The point clouds in your own dataset might not be suitable for RV projection. We discussed this problem in appendix.B *RV under Indoor and Outdoor Scenes* of [our paper](https://arxiv.org/pdf/2207.02605.pdf). You may check the validity of the generated RV images with the following visualization code. Reasonable RV images should be like the top row of **Segmentation GIF** in the [README](https://github.com/haibo-qiu/GFNet#gfnet---)
https://github.com/haibo-qiu/GFNet/blob/2f28cb4003480eaf7be024cca206cd1d7068a671/libs/utils/tools.py#L293-L304

**Comment by haibo-qiu** [comment]
Feel free to reopen this issue if you have any further questions.

**Comment by langdaoliu** [comment]
thank you.i got some mistakes in my rv labels.this bug has been fixed.

**Comment by haibo-qiu** [comment]
👍 Great
